set autoindent
set backspace=indent,eol,start
set colorcolumn=100
set cursorline
set fileencodings=utf-8,default,big5,ucs-bom,latin1
set hlsearch
set ignorecase
set incsearch
set nobackup
set noswapfile
set nowritebackup
set number
set ruler
set scrolloff=3
set shiftwidth=4
set showcmd
set smartcase
set smartindent
set t_Co=256
set tabpagemax=100
set tabstop=4
set timeoutlen=300
set wildmenu
